<?xml version="1.0" encoding="UTF-8"?>
<model xmlns="http://www.justep.com/model">
<action name="MyQuerryNameAction" global="false" procedure="MyQuerryNameProcedure"><label language="zh_CN">自建查询姓名</label>
<permission name="range" type="List"/>  
    <private name="concept" type="String" value="CHANGE_APPLY_INFO"/>  
    <private name="select" type="String" value="HR_BASE_INFO.oPERATORNAME as oPERATORNAME,HR_BASE_INFO1.oPERATORNAME as oPERATORNAME1,HR_BASE_INFO2.oPERATORNAME as oPERATORNAME2,CHANGE_APPLY_INFO,CHANGE_APPLY_INFO.CHANGE_APPLY_NOAPPLYNO as CHANGE_APPLY_NOAPPLYNO,CHANGE_APPLY_INFO.CHANGE_TITLETITLE as CHANGE_TITLETITLE,CHANGE_APPLY_INFO.PROJECT_IDID as PROJECT_IDID,CHANGE_APPLY_INFO.PROJECT_NAMENAME as PROJECT_NAMENAME,CHANGE_APPLY_INFO.CHANGE_OBJECTOBJECT as CHANGE_OBJECTOBJECT,CHANGE_APPLY_INFO.CHANGE_CONTENTCONTENT as CHANGE_CONTENTCONTENT,CHANGE_APPLY_INFO.CHANGE_REASONREASON as CHANGE_REASONREASON,CHANGE_APPLY_INFO.IMPACT_RANGERANGE as IMPACT_RANGERANGE,CHANGE_APPLY_INFO.POTENTIAL_RISKRISK as POTENTIAL_RISKRISK,CHANGE_APPLY_INFO.RESOLVE_RISKRISK as RESOLVE_RISKRISK,CHANGE_APPLY_INFO.IMPLEMENTATION_PROCESSPROCESS as IMPLEMENTATION_PROCESSPROCESS,CHANGE_APPLY_INFO.RESOURCES_NEEDEDNEEDED as RESOURCES_NEEDEDNEEDED,CHANGE_APPLY_INFO.CHANGE_TIMETIME as CHANGE_TIMETIME,CHANGE_APPLY_INFO.APPLY_PERSONPERSON as APPLY_PERSONPERSON,CHANGE_APPLY_INFO.APPLY_DATEDATE as APPLY_DATEDATE,CHANGE_APPLY_INFO.REASON_ASSESSMENTASSESSMENT as REASON_ASSESSMENTASSESSMENT,CHANGE_APPLY_INFO.RANGE_ASSESSMENTASSESSMENT as RANGE_ASSESSMENTASSESSMENT,CHANGE_APPLY_INFO.RISK_ASSESSMENTASSESSMENT as RISK_ASSESSMENTASSESSMENT,CHANGE_APPLY_INFO.PROCESS_ASSESSMENTASSESSMENT as PROCESS_ASSESSMENTASSESSMENT,CHANGE_APPLY_INFO.RESOURCE_ASSESSMENTASSESSMENT as RESOURCE_ASSESSMENTASSESSMENT,CHANGE_APPLY_INFO.TIME_ASSESSMENTASSESSMENT as TIME_ASSESSMENTASSESSMENT,CHANGE_APPLY_INFO.APPROVAL_STATUSSTATUS as APPROVAL_STATUSSTATUS,CHANGE_APPLY_INFO.ACCEPT_OPINIONOPINION as ACCEPT_OPINIONOPINION,case when CHANGE_APPLY_INFO.APPROVAL_STATUSSTATUS = 1 then '已审核' when CHANGE_APPLY_INFO.APPROVAL_STATUSSTATUS = 2 then '审核中' when CHANGE_APPLY_INFO.APPROVAL_STATUSSTATUS = 3 then '未审核' end  as QQ,CHANGE_APPLY_INFO.CHANGE_AUDITOR as CHANGE_AUDITOR,CHANGE_APPLY_INFO.CHANGE_AUDIT_DATE as CHANGE_AUDIT_DATE,CHANGE_APPLY_INFO.CHANGE_APPLY_DOC_NO as CHANGE_APPLY_DOC_NO,CHANGE_APPLY_INFO.MEMO as MEMO,CHANGE_APPLY_INFO.APPLY_APPROVER as APPLY_APPROVER,CHANGE_APPLY_INFO.APPLY_APPROVE_DATE as APPLY_APPROVE_DATE"/>  
    <private name="from" type="String" value="CHANGE_APPLY_INFO CHANGE_APPLY_INFO  optional  join HR_BASE_INFO HR_BASE_INFO on CHANGE_APPLY_INFO.APPLY_PERSONPERSON = HR_BASE_INFO optional  join HR_BASE_INFO HR_BASE_INFO1 on CHANGE_APPLY_INFO.CHANGE_AUDITOR = HR_BASE_INFO1 optional  join HR_BASE_INFO HR_BASE_INFO2 on CHANGE_APPLY_INFO.APPLY_APPROVER = HR_BASE_INFO2"/>  
    <private name="aggregate" type="String"/>  
    <private name="dataModel" type="String" value="/metrodetection/system_code/data"/>  
    <private name="fnModel" type="String"/>  
    <protected name="condition" type="String"/>  
    <public name="distinct" type="Boolean" value="false"/>  
    <public name="idColumn" type="String" value="CHANGE_APPLY_INFO"/>  
    <public name="filter" type="String"/>  
    <public name="limit" type="Integer"/>  
    <public name="offset" type="Integer"/>  
    <public name="columns" type="String"/>  
    <public name="orderBy" type="String"/>  
    <public name="aggregateColumns" type="String"/>  
    <public name="variables" type="Map"/> 
</action>
</model>