import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

import com.justep.system.data.KSQL;
import com.justep.system.data.Table;
import com.justep.system.process.ProcessUtils;



public class Jieyueshenqing {
	public static String jieyueshenqingFn() {
//		String taskTitle = "select P_DOCUMENTS_BORROW_RECORD.aPPLICATIONTIME as aPPLICATIONTIME," +
//				"P_DOCUMENTS_BORROW_RECORD.pFILENAME as pFILENAME,DOCUMENT_CATEGORY_CODE.dOCUMENTCATEGORYCNAME as dOCUMENTCATEGORYCNAME," +
//				"DOCUMENT_TYPE_CODE.dOCUMENTTYPECNAME as dOCUMENTTYPECNAME,P_DOCUMENTS_BORROW_RECORD.bORROWER as bORROWER1 " +
//				"from P_DOCUMENTS_BORROW_RECORD P_DOCUMENTS_BORROW_RECORD " +
//				"optional  join DOCUMENT_CATEGORY_CODE DOCUMENT_CATEGORY_CODE on P_DOCUMENTS_BORROW_RECORD.dOCUMENTCATEGORY = DOCUMENT_CATEGORY_CODE " +
//				"optional  join DOCUMENT_TYPE_CODE DOCUMENT_TYPE_CODE on P_DOCUMENTS_BORROW_RECORD.dOCUMENTTYPE = DOCUMENT_TYPE_CODE.dOCUMENTTYPE " +
//				"where DOCUMENTS_DESTROY_RECODE=:getProcessData1()";
		String data = ProcessUtils.getProcessData1();
		Integer d = Integer.parseInt(data);
		String taskTitle = "select DOCUMENT_CATEGORY_CODE," +
				"DOCUMENT_TYPE_CODE.dOCUMENTTYPE as dOCUMENTTYPE," +
				"P_DOCUMENTS_BORROW_RECORD.aPPLICATIONTIME as aPPLICATIONTIME," +
				"P_DOCUMENTS_BORROW_RECORD.pFILEID as pFILEID," +
				"P_DOCUMENTS_BORROW_RECORD.dOCUMENTCATEGORY as dOCUMENTCATEGORY," +
				"P_DOCUMENTS_BORROW_RECORD.dOCUMENTTYPE as dOCUMENTTYPE1," +
				"P_DOCUMENTS_BORROW_RECORD.pFILENAME as pFILENAME," +
				"P_DOCUMENTS_BORROW_RECORD.bORROWER as bORROWER," +
				"P_DOCUMENTS_BORROW_RECORD.rETURNDATE as rETURNDATE," +
				"P_DOCUMENTS_BORROW_RECORD.iNDEEDRETURNDATE as iNDEEDRETURNDATE," +
				"P_DOCUMENTS_BORROW_RECORD.mEMO as mEMO," +
				"DOCUMENT_CATEGORY_CODE.dOCUMENTCATEGORYCNAME as dOCUMENTCATEGORYCNAME," +
				"DOCUMENT_TYPE_CODE.dOCUMENTTYPECNAME as dOCUMENTTYPECNAME," +
				"HR_BASE_INFO.oPERATORNAME as oPERATORNAME," +
				"P_DOCUMENTS_BORROW_RECORD.bORROWER as bORROWER1," +
				"P_DOCUMENTS_ARCHIVE.aLLOWBORROW as aLLOWBORROW," +
				"HR_BASE_INFO.oPERATORNAME as oPERATORNAME1" +
				",HR_BASE_INFO.oPERATORNAME as oPERATORNAME2 " +
				"from P_DOCUMENTS_BORROW_RECORD P_DOCUMENTS_BORROW_RECORD " +
				"optional  join DOCUMENT_CATEGORY_CODE DOCUMENT_CATEGORY_CODE on P_DOCUMENTS_BORROW_RECORD.dOCUMENTCATEGORY = DOCUMENT_CATEGORY_CODE " +
				"optional  join DOCUMENT_TYPE_CODE DOCUMENT_TYPE_CODE on P_DOCUMENTS_BORROW_RECORD.dOCUMENTTYPE = DOCUMENT_TYPE_CODE.dOCUMENTTYPE " +
				"optional  join HR_BASE_INFO HR_BASE_INFO on P_DOCUMENTS_BORROW_RECORD.bORROWER = HR_BASE_INFO " +
				"optional  join P_DOCUMENTS_ARCHIVE P_DOCUMENTS_ARCHIVE on P_DOCUMENTS_BORROW_RECORD.pFILEID = P_DOCUMENTS_ARCHIVE " +
				"where P_DOCUMENTS_BORROW_RECORD="+d;
		Table tb = KSQL.select(taskTitle, null, "/metrodetection/system_code/data", null);
		Date aPPLICATIONTIME = (Date) tb.iterator().next().getValue("aPPLICATIONTIME");
		String dOCUMENTCATEGORYCNAME = (String) tb.iterator().next().getValue("dOCUMENTCATEGORYCNAME");
		String dOCUMENTTYPECNAME = (String) tb.iterator().next().getValue("dOCUMENTTYPECNAME");
		String sDocName = (String) tb.iterator().next().getValue("pFILENAME");
		DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
		String applicationtime = df.format(aPPLICATIONTIME);
		String res = "借阅时间："+applicationtime+"-文档借阅-文档科目:"+dOCUMENTCATEGORYCNAME+"-文档类别:"+dOCUMENTTYPECNAME+"-文档名称:"+sDocName;
//		String res = "销毁时间："+applicationtime+"--申请人："+bORROWER1+"文档销毁--文档科目:"+dOCUMENTCATEGORYCNAME+"-文档类别:"+dOCUMENTTYPECNAME+"-文档名称:"+pFILENAME;
		return res;
	}
}