<?xml version="1.0" encoding="utf-8"?>

<model xmlns="http://www.justep.com/model">  
  <action name="myTestProjectInfoAction" global="false" procedure="myTestProjectInfoProcedure"> 
    <label language="zh_CN">新建测试项目查询</label>  
    <permission name="range" type="List"/>  
    <private name="concept" type="String" value="TEST_PROJECT_INFO"/>  
    <private name="select" type="String" value="TEST_PROJECT_INFO,TEST_PROJECT_INFO.aPPLICATIONNO as aPPLICATIONNO,TEST_PROJECT_INFO.tESTSCHEMEID as tESTSCHEMEID,TEST_PROJECT_INFO.pROJECTNAME as pROJECTNAME,TEST_PROJECT_INFO.pROJECTTYPE as pROJECTTYPE,TEST_PROJECT_INFO.aSSIGNEDMANUFACTUREID as proASSIFACTUREID,TEST_PROJECT_INFO.cONTACTPERSON as cONTACTPERSON,TEST_APPLICATION_INFO,TEST_APPLICATION_INFO.aSSIGNEDMANUFACTUREID as aSSIGNEDMANUFACTUREID,TEST_APPLICATION_INFO.pRODUCTNAME as pRODUCTNAME,TEST_APPLICATION_INFO.dETECTIONOBJECTTYPE as dETECTIONOBJECTTYPE,TEST_APPLICATION_INFO.dEVICETYPE as dEVICETYPE,TEST_APPLICATION_INFO.dECTIONBASEDONNAME as dECTIONBASEDONNAME,TEST_APPLICATION_INFO.aPPLICATIONDATE as aPPLICATIONDATE,TEST_SCHEME_BASE_INFO,TEST_SCHEME_BASE_INFO.tESTSCHEMENAME as tESTSCHEMENAME,AFC_MANUFACTURER_INFO,AFC_MANUFACTURER_INFO.mANUFACTUREIDCNAME as mANUFACTUREIDCNAME,TEST_PROJECT_INFO.cONTACTMOBILE as cONTACTMOBILE,TEST_PROJECT_INFO.cONTACTTELEPHONE as cONTACTTELEPHONE,TEST_PROJECT_INFO.cONTACTEMAIL as cONTACTEMAIL,TEST_PROJECT_INFO.nOTIFYTYPE as nOTIFYTYPE,TEST_PROJECT_INFO.lINEID as lINEID,TEST_PROJECT_INFO.bUSINESSID as bUSINESSID,TEST_PROJECT_INFO.mANUFACTUREID as mANUFACTUREID1,TEST_PROJECT_INFO.pROJECTDATE as pROJECTDATE,TEST_PROJECT_INFO.eNDINGDATE as eNDINGDATE,TEST_PROJECT_INFO.pROJECTMANAGER as pROJECTMANAGER,TEST_PROJECT_INFO.qAMANAGER as qAMANAGER,TEST_PROJECT_INFO.tESTMANAGER as tESTMANAGER,TEST_PROJECT_INFO.tECHMANAGER as tECHMANAGER,TEST_PROJECT_INFO.mAKEDATE as mAKEDATE,TEST_PROJECT_INFO.eXECUTESTATE as eXECUTESTATE,TEST_PROJECT_INFO.mEMO as mEMO,BUSINESS_TYPE_CODE,BUSINESS_TYPE_CODE.bUSINESSIDCNAME as bUSINESSIDCNAME,HR_BASE_INFO.oPERATORNAME as oPERATORNAME,HR_BASE_INFO,DETECTION_OBJECT_TYPE,DETECTION_OBJECT_TYPE.dETECTIONOBJECTCNAME as dETECTIONOBJECTCNAME,DEVICE_TYPE_CODE.dETECTIONOBJECTTYPE as dETECTIONOBJECTTYPE1,DEVICE_TYPE_CODE.dEVICETYPE as dEVICETYPE1,DEVICE_TYPE_CODE.dEVICETYPECNAME as dEVICETYPECNAME"/>  
    <private name="from" type="String" value="TEST_PROJECT_INFO TEST_PROJECT_INFO  optional  join TEST_APPLICATION_INFO TEST_APPLICATION_INFO on TEST_PROJECT_INFO.aPPLICATIONNO = TEST_APPLICATION_INFO optional  join TEST_SCHEME_BASE_INFO TEST_SCHEME_BASE_INFO on TEST_PROJECT_INFO.tESTSCHEMEID = TEST_SCHEME_BASE_INFO optional  join AFC_MANUFACTURER_INFO AFC_MANUFACTURER_INFO on TEST_PROJECT_INFO.aSSIGNEDMANUFACTUREID = AFC_MANUFACTURER_INFO optional  join BUSINESS_TYPE_CODE BUSINESS_TYPE_CODE on TEST_PROJECT_INFO.bUSINESSID = BUSINESS_TYPE_CODE optional  join HR_BASE_INFO HR_BASE_INFO on TEST_PROJECT_INFO.pROJECTMANAGER = HR_BASE_INFO optional  join DETECTION_OBJECT_TYPE DETECTION_OBJECT_TYPE on TEST_APPLICATION_INFO.dETECTIONOBJECTTYPE = DETECTION_OBJECT_TYPE optional  join DEVICE_TYPE_CODE DEVICE_TYPE_CODE on TEST_APPLICATION_INFO.dETECTIONOBJECTTYPE = DEVICE_TYPE_CODE.dETECTIONOBJECTTYPE AND TEST_APPLICATION_INFO.dEVICETYPE = DEVICE_TYPE_CODE.dEVICETYPE"/>  
    <private name="aggregate" type="String"/>  
    <private name="dataModel" type="String" value="/metrodetection/system_code/data"/>  
    <private name="fnModel" type="String"/>  
    <protected name="condition" type="String"/>  
    <public name="distinct" type="Boolean" value="false"/>  
    <public name="idColumn" type="String" value="TEST_PROJECT_INFO"/>  
    <public name="filter" type="String"/>  
    <public name="limit" type="Integer"/>  
    <public name="offset" type="Integer"/>  
    <public name="columns" type="String"/>  
    <public name="orderBy" type="String" value="TEST_PROJECT_INFO desc"/>  
    <public name="aggregateColumns" type="String"/>  
    <public name="variables" type="Map"/> 
  </action> 
</model>
